---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: Jessie Chen
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---

::: {.callout-important}
## Memo format

Like all other submissions for this course, we expect the memo to be neat and well organized.

You should make this document your own. This is a template. To help with this we have added a date to the yaml above (good whenever writing memos). You should remove this block when making this document your own.

:::

::: {.callout-tip icon=false}

## Github Repo Link

To link to your github **repo**sitory, appropriately edit the example link below. Meaning replace `https://your-github-repo-url` with your github repo url. Suggest verifying the link works before submitting.

[My Repo Link](https://github.com/stat301-1-2023-fall/final-project-1-Jchench)

:::

::: {.callout-warning}
GitHub (free account) cannot store large files. If you try to commit and push a large dataset you will have an ERROR! Any file over 100 MB (100,000 KB) needs to be added to the `.gitignore` file BEFORE committing.

**We may need to do that for files in your final project!**
:::

## Data source

```{r}
# Loading data and packages:
library(tidyverse)
library(naniar)

spotify_data_top <- 
  read_csv("data/ATop 1990-2022.csv")

spotify_streams <- 
  read_csv("data/spotify_streams.csv")
```

The first data set I am using Spotify-made playlists that include between 50-130 tracks of the most popular songs each year from 1990-2022. ^[]

## Why this data

I chose to use these datasets because I think it would be interesting to look at the songs that were considered "popular" throughout the years form 1990-2022. The `spotify_data_top` has a lot of interesting information on each individual song (e.g. dancebility, energy, and key), and I think it could be useful to analyze if there are any correlations among these elements and "popularity". The `spotify_streams` dataset provides useful a more concrete measure of "popularity" by collecting the number of streams for each song. Thus, I think it would be helpful to merge these two datasets together to look at the number of streams as an indicator of popularity. 

## Data quality & complexity check

The datasets seem to be sufficiently complex. `spotify_data_top` has 2610 rows and 26 variable and `spotify_streams` has 11084 rows and 9 variables.

## Potential data issues

Blah blah blah

## Misc

Blah Blah
